services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_backend
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/healthcare_chatbot
    volumes:
      - ./backend:/app  # Bind mount to enable hot-reloading
    depends_on:
      - db
    networks:
      - healthcare_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app  # Bind mount to enable hot-reloading
      - /app/node_modules  # Prevent node_modules from being overwritten by the bind mount
    stdin_open: true
    tty: true
    networks:
      - healthcare_network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare_chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthcare_network

volumes:
  postgres_data:

networks:
  healthcare_network:
