---
version: '3.8'

services:
  health_app:
    build: .
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: